#%RAML 1.0 DataType
  properties:
    libraryCode:
      type: string
      required: true
      description: library code
    libraryBranch:
      type: string
      required: true
      description: library code