#%RAML 1.0 DataType
properties:
  libraryCode:
    type: string
    example: 'weu123'
  address:
    type: string
    example: 'hyderabad'  
  phoneNumber:
    type: integer
    example: 9872343454  
  email:
    type: string
    example: sudhiw@gmail.com