#%RAML 1.0 DataType

#%RAML 1.0 DataType
properties:
          libraryCode:
            type: string
            example: 'de5457'
          title:
            type: string
            example: 'half girlfriend' 
          author:
            type: string
            example: 'chetan bhagat'