#%RAML 1.0 Trait

headers:
      Client_id:
        type: string
        description: clientId
      client_secret:
        type: string
        description: client secret
      x-correlation-ID:
        type: string
        description: transaction id