#%RAML 1.0
title: process-ibs-library
baseUri: http://process-ibs-library.cloudhib.io
mediaType: 
- application/json
protocols:
  - HTTP

traits:
  headerInfo: !include /exchange_modules/e28b1056-fd3b-4c9c-8a6e-690b26b38556/common-headers/1.0.0/common-headers.raml
  queryParams: !include /traits/queryPtrait.raml
types:
  get-libraries: !include /dataTypes/get-libraries-dataType.raml
  post-book-request: !include /dataTypes/post-book-req-dataType.raml
  get-libraryId: !include /dataTypes/get-libraryId-dataType.raml
/libraries:
  get: 
    is:
    - headerInfo:
    description: this is to fetch all library details from db
    responses:
      200:
        body:
          application/json:
            type: get-libraries             
            example: !include /examples/getLibrariesResponseExample.raml
      400:
        body:
          application/json:
            example: 
             {
               'errorCode': '404',
               'description': 'unauthorized'
             }

  /{libraryId}:
    get: 
      is:
      - headerInfo:
      description: fetch library based on library Id
      responses:
        200:
          body:
            application/json:
              type: get-libraryId 
              example: !include /examples/getByIdResponseExample.raml

/books:   
  post: 
    is:
    - headerInfo:
    body:
      application/json:
        type: post-book-request
        example: !include /examples/postBooksRequestExample.raml
    responses:
      201:
        body:
          application/json:
            example:
              {
                'result': 'book added successfully',
                'Book code': 'Bk123'
              }
  get:
    is:
    - headerInfo
    - queryParams
    responses:
      200:
        body:
          application/json:
            example: !include /examples/getBooksBasedOnRatingExample.raml
                                    
                     

              